version: 2.1
orbs:
  architect: giantswarm/architect@0.8.5

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push azure-logs-workspace-app chart"
          app_catalog: "giantswarm-azure-test-catalog"
          app_catalog_test: "giantswarm-azure-test-catalog"
          chart: "azure-logs-workspace-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
