{{- if or .Values.fluentd.aws.cloudWatch.enabled .Values.fluentd.aws.S3.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fluentd.name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fluentd.name }}
data:
  fluent.conf: |-
    # listen for logs from fluentbit
    <source>
      @type forward
      bind 0.0.0.0
      port {{ .Values.fluentd.port }}
    </source>

    <match kubernetes.**>
      @type copy
      
      {{- if .Values.fluentd.aws.cloudWatch.enabled }}
      <store>
        @type              cloudwatch_logs
        @log_level         {{ .Values.fluentd.logLevel }}
        log_group_name     {{ .Values.fluentd.aws.cloudWatch.logGroupName }}
        log_stream_name    {{ .Values.fluentd.aws.cloudWatch.logStreamName }}-containers
        auto_create_stream true
      </store>
      {{- end}}

      {{- if .Values.fluentd.aws.S3.enabled }}
      <store>
        @type                 s3
        @log_level            {{ .Values.fluentd.logLevel }}
        s3_bucket             {{ .Values.fluentd.aws.S3.bucketName }}
        s3_region             {{ .Values.fluentd.aws.S3.bucketRegion }}
        path                  {{ .Values.fluentd.aws.S3.bucketPathPrefix }}-containers/
        s3_object_key_format  {{ .Values.fluentd.aws.S3.s3_object_key_format }}
        {{- if .Values.fluentd.aws.S3.grant_full_control }}
        grant_full_control    {{ .Values.fluentd.aws.S3.grant_full_control }}
        {{- end }}
        check_bucket          false
        check_object          false
        check_apikey_on_start false
        {{- if not .Values.fluentd.aws.kiam }}
        <assume_role_credentials>
          role_arn            arn:aws:iam::{{ .Values.fluentd.aws.S3.account }}:role/{{ .Values.fluentd.aws.S3.role }}
          role_session_name   fluentd
        </assume_role_credentials>
        {{- end }}
        <buffer tag,time>
          @type               file
          path                /var/run/fluentd/buffer/s3/containers
          timekey             3600 # 1 hour partition
          timekey_wait        10m
          timekey_use_utc     true
          chunk_limit_size    256m
        </buffer>
        <format>
          @type               json
        </format>
      </store>
      {{- end}}
    </match>

    <match syslog.**>
      @type copy
      
      {{- if .Values.fluentd.aws.cloudWatch.enabled }}
      <store>
        @type              cloudwatch_logs
        @log_level         {{ .Values.fluentd.logLevel }}
        log_group_name     {{ .Values.fluentd.aws.cloudWatch.logGroupName }}
        log_stream_name    {{ .Values.fluentd.aws.cloudWatch.logStreamName }}-syslog
        auto_create_stream true
      </store>
      {{- end}}

      {{- if .Values.fluentd.aws.S3.enabled }}
      <store>
        @type                 s3
        @log_level            {{ .Values.fluentd.logLevel }}
        s3_bucket             {{ .Values.fluentd.aws.S3.bucketName }}
        s3_region             {{ .Values.fluentd.aws.S3.bucketRegion }}
        path                  {{ .Values.fluentd.aws.S3.bucketPathPrefix }}-syslog/
        s3_object_key_format  {{ .Values.fluentd.aws.S3.s3_object_key_format }}
        {{- if .Values.fluentd.aws.S3.grant_full_control }}
        grant_full_control    {{ .Values.fluentd.aws.S3.grant_full_control }}
        {{- end }}
        check_bucket          false
        check_object          false
        check_apikey_on_start false
        {{- if not .Values.fluentd.aws.kiam }}
        <assume_role_credentials>
          role_arn            arn:aws:iam::{{ .Values.fluentd.aws.S3.account }}:role/{{ .Values.fluentd.aws.S3.role }}
          role_session_name   fluentd
        </assume_role_credentials>
        {{- end }}
        <buffer tag,time>
          @type               file
          path                /var/run/fluentd/buffer/s3/syslog
          timekey             3600 # 1 hour partition
          timekey_wait        10m
          timekey_use_utc     true
          chunk_limit_size    256m
        </buffer>
        <format>
          @type               json
        </format>
      </store>
      {{- end}}
    </match>

    <match audit.kubernetes.**>
      @type copy
      
      {{- if .Values.fluentd.aws.cloudWatch.enabled }}
      <store>
        @type              cloudwatch_logs
        @log_level         {{ .Values.fluentd.logLevel }}
        log_group_name     {{ .Values.fluentd.aws.cloudWatch.logGroupName }}
        log_stream_name    {{ .Values.fluentd.aws.cloudWatch.logStreamName }}-kubernetes-audit
        auto_create_stream true
      </store>
      {{- end}}

      {{- if .Values.fluentd.aws.S3.enabled }}
      <store>
        @type                 s3
        @log_level            {{ .Values.fluentd.logLevel }}
        s3_bucket             {{ .Values.fluentd.aws.S3.bucketName }}
        s3_region             {{ .Values.fluentd.aws.S3.bucketRegion }}
        path                  {{ .Values.fluentd.aws.S3.bucketPathPrefix }}-kubernetes-audit/
        s3_object_key_format  {{ .Values.fluentd.aws.S3.s3_object_key_format }}
        {{- if .Values.fluentd.aws.S3.grant_full_control }}
        grant_full_control    {{ .Values.fluentd.aws.S3.grant_full_control }}
        {{- end }}
        check_bucket          false
        check_object          false
        check_apikey_on_start false
        {{- if not .Values.fluentd.aws.kiam }}
        <assume_role_credentials>
          role_arn            arn:aws:iam::{{ .Values.fluentd.aws.S3.account }}:role/{{ .Values.fluentd.aws.S3.role }}
          role_session_name   fluentd
        </assume_role_credentials>
        {{- end }}
        <buffer tag,time>
          @type               file
          path                /var/run/fluentd/buffer/s3/audit_kubernetes
          timekey             3600 # 1 hour partition
          timekey_wait        10m
          timekey_use_utc     true
          chunk_limit_size    256m
        </buffer>
        <format>
          @type               json
        </format>
      </store>
      {{- end}}
    </match>

    <match audit.ssh.**>
      @type copy
      
      {{- if .Values.fluentd.aws.cloudWatch.enabled }}
      <store>
        @type              cloudwatch_logs
        @log_level         {{ .Values.fluentd.logLevel }}
        log_group_name     {{ .Values.fluentd.aws.cloudWatch.logGroupName }}
        log_stream_name    {{ .Values.fluentd.aws.cloudWatch.logStreamName }}-ssh-audit
        auto_create_stream true
      </store>
      {{- end}}

      {{- if .Values.fluentd.aws.S3.enabled }}
      <store>
        @type                 s3
        @log_level            {{ .Values.fluentd.logLevel }}
        s3_bucket             {{ .Values.fluentd.aws.S3.bucketName }}
        s3_region             {{ .Values.fluentd.aws.S3.bucketRegion }}
        path                  {{ .Values.fluentd.aws.S3.bucketPathPrefix }}-ssh/
        s3_object_key_format  {{ .Values.fluentd.aws.S3.s3_object_key_format }}
        {{- if .Values.fluentd.aws.S3.grant_full_control }}
        grant_full_control    {{ .Values.fluentd.aws.S3.grant_full_control }}
        {{- end }}
        check_bucket          false
        check_object          false
        check_apikey_on_start false
        {{- if not .Values.fluentd.aws.kiam }}
        <assume_role_credentials>
          role_arn            arn:aws:iam::{{ .Values.fluentd.aws.S3.account }}:role/{{ .Values.fluentd.aws.S3.role }}
          role_session_name   fluentd
        </assume_role_credentials>
        {{- end }}
        <buffer tag,time>
          @type               file
          path                /var/run/fluentd/buffer/elasticsearch/ssh
          timekey             3600 # 1 hour partition
          timekey_wait        10m
          timekey_use_utc     true
          chunk_limit_size    256m
        </buffer>
        <format>
          @type               json
        </format>
      </store>
      {{- end}}
    </match>
{{- end }}
