{{- if or .Values.fluentd.aws.cloudWatch.enabled .Values.fluentd.aws.S3.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
