fluentd:
  aws:
    kiam: true
    S3:
      enabled: true
      bucketName: "my-cluster-logs"
      bucketRegion: "eu-central-1"
      bucketPathPrefix: "gs-"
      account: "00000000000"
      role: "my-role"
      s3_object_key_format: "%{path}%{time_slice}_%{index}.%{file_extension}"
  