apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.fluentbit.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fluentbit.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.fluentbit.name }}
  template:
    metadata:
      annotations:
        releasetime: {{ $.Release.Time }}
      labels:
        app: {{ .Values.fluentbit.name }}
    spec:
      tolerations:
      # Tolerate master taint
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: {{ .Values.fluentbit.name }}
      securityContext:
        runAsUser: {{ .Values.fluentbit.userID }}
        runAsGroup: {{ .Values.fluentbit.groupID }}
      containers:
      - name: {{ .Values.fluentbit.name }}
        image: {{ .Values.image.registry }}/{{ .Values.fluentbit.image.name }}:{{ .Values.fluentbit.image.tag }}
        env:
        - name: FLUENTD_HOST
          value: "{{ .Values.fluentd.name }}.{{ .Release.Namespace }}.svc"
        - name: FLUENTD_PORT
          value: "{{ .Values.fluentd.port }}"
        {{- if .Values.fluentd.azure.logAnalytics.enabled }}
        - name: FLUENT_AZURE_WORKSPACE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.fluentbit.name }}-secret
              key: WorkspaceID
        - name: FLUENT_AZURE_WORKSPACE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.fluentbit.name }}-secret
              key: WorkspaceKey
        {{- end }}
        {{- if and .Values.fluentd.elasticsearch.enabled .Values.fluentd.elasticsearch.secured }}
        - name: FLUENT_ELASTICSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.fluentbit.name }}-secret
              key: ElasticsearchUser
        - name: FLUENT_ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.fluentbit.name }}-secret
              key: ElasticsearchPassword
        {{- end }}
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: {{ .Values.fluentbit.port }}
          initialDelaySeconds: 10
        readinessProbe:
          tcpSocket:
            port: {{ .Values.fluentbit.port }}
          initialDelaySeconds: 10
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varrunfluentbit
          mountPath: /var/run/fluent-bit
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        ## Needed for syslog to work as the syslog plugins needs this id
        - name: etcmachineid	
          mountPath: /etc/machine-id	
          readOnly: true	
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varrunfluentbit
        hostPath:
          path: /var/run/fluent-bit
          type: DirectoryOrCreate
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: {{ .Values.fluentbit.name }}-config
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
