kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.fluentbit.name }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.fluentbit.name }}
  ingress:
  - ports:
    - port: {{ .Values.fluentbit.port }}
      protocol: {{ .Values.fluentbit.protocol }}
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
