{{- if or .Values.fluentd.azure.logAnalytics.enabled .Values.fluentd.elasticsearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fluentbit.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.fluentbit.name }}
stringData:
  {{- if .Values.fluentd.azure.logAnalytics.enabled }}
  WorkspaceKey: {{ .Values.fluentd.azure.logAnalytics.sharedKey | quote }}
  WorkspaceID: {{ .Values.fluentd.azure.logAnalytics.workspaceId | quote }}
  {{- end}} 
  {{- if and .Values.fluentd.elasticsearch.enabled .Values.fluentd.elasticsearch.secured}}
  ElasticsearchUser: {{ .Values.fluentd.elasticsearch.user | quote }}
  ElasticsearchPassword: {{ .Values.fluentd.elasticsearch.password | quote }}
  {{- end}} 
{{- end }}
